### ISSUE TITLE
Android N FileUriExposedException:  exposed beyond app through ClipData.Item.getUri()

### ISSUE THREAD

**Issue by noamamiran** [tungdx/android-media-picker#11]
On Android N, When trying to capture image from camera the following ex raised: FileUriExposedException:  exposed beyond app through ClipData.Item.getUri()

**Comment by noamamiran** [comment]
https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en

**Comment by saeid-pm** [comment]
try add this code before capture image : 

StrictMode.VmPolicy.Builder builder = new StrictMode.VmPolicy.Builder();
StrictMode.setVmPolicy(builder.build());

**Comment by BambangHeriSetiawan** [comment]
StrictMode.VmPolicy.Builder builder = new StrictMode.VmPolicy.Builder();
StrictMode.setVmPolicy(builder.build());

that is work for me.

**Comment by cristian9016** [comment]
this solution worked!! thanks.

**Comment by Albatoul** [comment]
You are genius

**Comment by toantk238** [comment]
Oh, I thought I have solved this issue. Now this still happens on Android N ?

**Comment by vanyasem** [comment]
That's a dirty workaround and not a proper solution. Refer to https://stackoverflow.com/questions/48117511/exposed-beyond-app-through-clipdata-item-geturi for more details

**Comment by PrasanthKumarKatta** [comment]
```
     Caused by: java.lang.SecurityException: 
Permission Denial: opening provider android.support.v4.content.FileProvider from ProcessRecord{24ff435 15339:com.android.gallery3d/u0a44} (pid=15339, uid=10044) that is not exported from uid 10138
```

**Comment by PrasanthKumarKatta** [comment]
> StrictMode.VmPolicy.Builder builder = new StrictMode.VmPolicy.Builder();
> StrictMode.setVmPolicy(builder.build());
> 
> that is work for me.

     Caused by: java.lang.SecurityException: Permission Denial: opening provider android.support.v4.content.FileProvider from ProcessRecord{24ff435 15339:com.android.gallery3d/u0a44} (pid=15339, uid=10044) that is not exported from uid 10138


ava.lang.IllegalStateException: Binder has been finalized!
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:622)

**Comment by abhishek-svc** [comment]
@toantk238

**Comment by aasinationskie** [comment]
StrictMode.VmPolicy.Builder builder = new StrictMode.VmPolicy.Builder();
StrictMode.setVmPolicy(builder.build());
thsi work but by using this the security policy will become week.
