### ISSUE TITLE
Android M permission model

### ISSUE THREAD

**Issue by baphna** [tungdx/android-media-picker#3]
Got this error:                                                                      Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=22380, uid=10304 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()

You need to incorporate android M permission model to support devices traget api 23

**Comment by tungdx** [comment]
Thanks for your comment. I just committed a new code to support Android M permission. Hope it helps
